WITH_EDITOR = true
target("engine")
    add_defines("ENGINE_ROOT="..os.curdir():gsub("\\", "\\\\"),{public = false})
    add_headerfiles("include/*.natvis","include/engine/**.h")
    add_includedirs("include", {public = true})
    set_kind("shared")
    set_group("Engine")
    add_rules("engine.api")
    add_files("src/engine/**.cpp")
target("editor")
    set_kind("shared")
    set_group("Engine")
    add_rules("engine.api")
    add_headerfiles("include/editor/**.h","assets/noesis/*.xaml")
    add_includedirs("include")
    add_files("src/editor/**.cpp")
    add_deps("engine", {public = true})
includes("xmake/xmake.lua")
includes("3rdparty/xmake.lua")
includes("tools/xmake.lua")
includes("modules/xmake.lua")